
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:grace_church/feature/home/domaine/entities/request/home_request.dart';
import 'package:grace_church/feature/home/domaine/entities/response/home_response.dart';
import 'package:grace_church/feature/home/page/bloc/rapport_cellule.dart/form_sassistance_bloc.dart';
part 'rapport_cellule_event.freezed.dart';

@freezed
class RapportCelluleRequestSectionAdministrationEvent with _$RapportCelluleRequestSectionAdministrationEvent {
   factory RapportCelluleRequestSectionAdministrationEvent.changeCodeZone(String codeZone ) = ChangeCodeZoneRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeFullNameRespoZone(String fullNameRespoZone ) = ChangeFullNameRespoZoneRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeContactRespoZone(String contactRespoZone ) = ChangeContactRespoZoneRapportCelluleRequestSectionAdministrationEvent;

   factory RapportCelluleRequestSectionAdministrationEvent.changeCodeSecteur(String codeSecteur ) = ChangeCodeSecteurRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeFullNameRespoSecteur(String fullNameRespoSecteur ) = ChangeFullNameRespoSecteurRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeContactRespoSecteur(String contactRespoSecteur ) = ChangeContactRespoSecteurRapportCelluleRequestSectionAdministrationEvent;

   factory RapportCelluleRequestSectionAdministrationEvent.changeCodeCellule(String codeCellule ) = ChangeCodeCelluleRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeFullNameRespoCellule(String fullNameRespoCellule ) = ChangeFullNameRespoCelluleRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeContactRespoCellule(String contactRespoCellule ) = ChangeContactRespoCelluleRapportCelluleRequestSectionAdministrationEvent;

   factory RapportCelluleRequestSectionAdministrationEvent.changeJourCellule(String jourCellule ) = ChangeJourCelluleRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeOffrande(String offrande ) = ChangeOffrandeRapportCelluleRequestSectionAdministrationEvent;

   factory RapportCelluleRequestSectionAdministrationEvent.changeNombreBaptiser(String nombreBaptiser ) = ChangeNombreBaptiserRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeNombreNonBaptiser(String nombreNonBaptiser ) = ChangeNombreNonBaptiserRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.changeNombreListDicipleCellule(List<DiscipleCellule> discipleCelluleResponse ) = ChangeNombreListDicipleCelluleRapportCelluleRequestSectionAdministrationEvent;
   factory RapportCelluleRequestSectionAdministrationEvent.submit() = SubmitRapportCelluleRequestSectionAdministrationEvent;

}



@freezed
class RapportCelluleRequestSectionAssistanceEvent with _$RapportCelluleRequestSectionAssistanceEvent {
   factory RapportCelluleRequestSectionAssistanceEvent.changeNombreBaptiser(String nombreBaptiser ) = ChangeNombreBaptiserRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.updateSectionId(String id) = RapportCelluleRequestSectionAssistanceEventUpdateSectionId;
   factory RapportCelluleRequestSectionAssistanceEvent.changeNomBaptiserStatic(List<RequestHumaneSectionAssistance> nomBaptiserStat ) = ChangeNomBaptiserStaticRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.changeNoveauBaptiser(List<RequestHumaneSectionAssistance> nouveauBaptiserStat ) = ChangeNoveauBaptiserRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.changeInviter(List<RequestHumaneSectionAssistance> inviterStat ) = ChangeInviterRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.changeFormation(List<RequestHumaneSectionAssistance> formationStat ) = ChangeFormationRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.changeSectionVisite(List<RequestHumaneSectionAssistance> sectionVisite ) = ChangeSectionVisiteRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.changeSectionActivite(List<RequestHumaneSectionAssistance> sectionActivite ) = ChangeSectionActiviteRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.changeSectionOuvrier(List<RequestHumaneSectionAssistance> sectionOuvrier ) = ChangeSectionOuvrierRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.changeAutres(List<RequestHumaneSectionAssistance> autres ) = ChangeAutresRapportCelluleRequestSectionAssistanceEvent;
   factory RapportCelluleRequestSectionAssistanceEvent.submit() = SubmitRapportCelluleRequestSectionAssistanceEvent;


}


